const asyncWrapper = (fn) => {
  return async (req, res, next) => {
    try {
      await fn(req, res, next);
    } catch (error) {
      next(error);
    }
  };
};

//next(error) will pass the error to the error handling middleware

module.exports = asyncWrapper;
